development:
  adapter: redis
  url: <%= ENV.fetch("REDIS_URL") { "redis://localhost:6379/1" } %>
  channel_prefix: rails-social_network_development

test:
  adapter: redis

production:
  adapter: redis
  url: redis://redistogo:626c96805a9b3b221d00fffe78b1f7c1@pike.redistogo.com:11229/
  channel_prefix: rails-social_network_production